version: '3.8'
services:
  client:
    build: ./client
    ports:
      - 8080:8080
    environment:
      - VUE_APP_SERVER=https://muz-060227d0c5a7.herokuapp.com/
    volumes:
      - ./client:/node_modules
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb://mongo:27017/muz-dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
